# Generated by Django 4.0.4 on 2022-07-11 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshorter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='source_url',
            field=models.CharField(max_length=500, validators=[django.core.validators.MinValueValidator(8)]),
        ),
    ]
