# Generated by Django 4.0.4 on 2022-07-12 22:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshorter', '0002_alter_url_source_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='source_url',
            field=models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
