# Generated by Django 4.0.3 on 2022-07-19 21:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(8)])),
                ('url_id', models.CharField(max_length=20)),
            ],
        ),
    ]
