# Generated by Django 4.0.3 on 2022-07-19 22:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='source_url',
            field=models.CharField(max_length=500, unique=True, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='url',
            name='url_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
