# Generated by Django 4.0.3 on 2022-07-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorter', '0003_alter_url_source_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url_id',
            field=models.CharField(max_length=20),
        ),
    ]
